MVIT:
  DROPPATH_RATE: 0.3
#  DIM_MUL: [[2, 2.0], [4, 2.0], [6, 2.0]]
#  HEAD_MUL: [[2, 2.0], [4, 2.0], [6, 2.0]]
  DIM_MUL: [ [ 1, 2.0 ], [ 3, 2.0 ]]
  HEAD_MUL: [ [ 1, 2.0 ], [ 3, 2.0 ]]
#  DIM_MUL: [  [ 3, 2.0 ] ]
#  HEAD_MUL: [ [ 3, 2.0 ] ]
  POOL_KVQ_KERNEL: [3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [4, 4]
#  POOL_Q_STRIDE: [[0, 1, 1], [1, 2, 2], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1], [6, 1, 1], [7, 1, 1], [8, 2, 2], [9, 1, 1]]
#  DEPTH: 16
#  POOL_Q_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1], [6, 1, 1], [7, 1, 1], [8, 2, 2], [9, 1, 1], [10, 1, 1], [11, 1, 1], [12, 1, 1], [13, 1, 1], [14, 1, 1], [15, 1, 1]]
#  POOL_T_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 1, 1], [4, 1, 1], [5, 1, 1], [6, 1, 1], [7, 1, 1], [8, 1, 1], [9, 1, 1], [10, 1, 1], [11, 1, 1], [12, 1, 1], [13, 1, 1], [14, 1, 1], [15, 1, 1]]
#  SAL_POOL_Q_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1], [6, 1, 1], [7, 1, 1], [8, 2, 2], [9, 1, 1], [10, 1, 1], [11, 1, 1], [12, 1, 1], [13, 1, 1], [14, 1, 1], [15, 1, 1]]
#  DEPTH: 9
#  POOL_Q_STRIDE: [ [ 0, 1, 1 ], [ 1, 1, 1 ], [ 2, 2, 2 ], [ 3, 1, 1 ], [ 4, 2, 2], [ 5, 1, 1], [6, 2, 2], [7, 1, 1], [8, 1, 1] ]
#  POOL_T_STRIDE: [ [ 0, 1, 1 ], [ 1, 1, 1 ], [ 2, 1, 1 ], [ 3, 1, 1 ], [ 4, 1, 1 ], [ 5, 1, 1 ], [6, 1, 1], [7, 1, 1], [8, 1, 1] ]
#  SAL_POOL_Q_STRIDE: [ [ 0, 1, 1 ], [ 1, 1, 1 ], [ 2, 1, 1 ], [ 3, 1, 1], [ 4, 1, 1 ], [ 5, 1, 1] , [6, 1, 1], [7, 1, 1], [8, 1, 1]]
#  DEPTH: 6
#  POOL_Q_STRIDE: [[0, 1, 1], [1, 2, 2], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1]]
#  POOL_T_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 1, 1], [4, 1, 1], [5, 1, 1]]
#  SAL_POOL_Q_STRIDE: [[0, 1, 1], [1, 2, 2], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1]]

  DEPTH: 4
  POOL_Q_STRIDE: [[0, 1, 1], [1, 2, 2], [2, 1, 1], [3, 1, 1]]
  POOL_T_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 1, 1]]
  SAL_POOL_Q_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 1, 1]]

  SAL_POOL_KVQ_KERNEL: [3, 3]
  SAL_POOL_KV_STRIDE_ADAPTIVE: [4, 4]
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.00003
#  BASE_LR: 0.00035
  LR_POLICY: cosine
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
#  OPTIMIZING_METHOD: adam
#  OPTIMIZING_METHOD: sgd
  CLIP_GRAD_L2NORM: 1.0
