# dirpath1 = u'./data/head-orientation/dataset1'
# dirpath2 = u'./data/head-orientation/dataset2/Experiment_1'
dirpath1 = u'E:/dataset/360-degree_video_head_movement_dataset/dataset'
dirpath2 = u'E:/dataset/vr_dataset/Experiment_1'
ext1 = '.txt'
ext2 = '.csv'